### ISSUE TITLE
Any effects on Private-Detector with TensorFlow Addon Wind Down?

### ISSUE THREAD

**Issue by Chebulex** [bumble-tech/private-detector#10]
Hello guys,
I hope this is the right place for that. TensorFlow Addons will be [discontinued](https://github.com/tensorflow/addons/issues/2807) as of May 2024. I wondered if this will have any effect on this project? And if so what could those be?

**Comment by Steeeephen** [comment]
Hmm didn't think of that, thanks for the heads up!

From what I can see, it will _technically_ affect the project as the repo does use TFA - but I don't think it's a big problem

* TFA will still (assumedly) work with current TF versions, so even in the worst case we'll be able to use the pinned versions to finetune the model
* The main feature/value of the project is the savedmodel/frozen model rather than the training code, which should still be usable in future versions without TFA
* We don't use TFA for anything too crazy. By the time 2024 rolls around, I'd hope that they'll be included with TF/keras anyway so the transition should be easy enough

So yeah it will affect some things, but I don't think it's a massive issue - especially for the people who only use the pretrained model

**Comment by FurkanGozukara** [comment]
I just tested this and the results are terrible :/

it cant classify sexy images at all

**Comment by Steeeephen** [comment]
> I just tested this and the results are terrible :/
> 
> it cant classify sexy images at all 

Hi @FurkanGozukara 

Thanks for the feedback!

Can I ask what kind of images you're testing the model on? Bearing in mind that this is not necessarily meant to be a general NSFW/sexual image classifier, but is instead specifically tuned to detect cyberflashing - meaning the training set is reflective of the types of images that are generally used in cyberflashing

https://bumble.com/the-buzz/bumble-open-source-private-detector-ai-cyberflashing-dick-pics

**Comment by FurkanGozukara** [comment]
> > I just tested this and the results are terrible :/
> > it cant classify sexy images at all
> 
> Hi @FurkanGozukara
> 
> Thanks for the feedback!
> 
> Can I ask what kind of images you're testing the model on? Bearing in mind that this is not necessarily meant to be a general NSFW/sexual image classifier, but is instead specifically tuned to detect cyberflashing - meaning the training set is reflective of the types of images that are generally used in cyberflashing
> 
> https://bumble.com/the-buzz/bumble-open-source-private-detector-ai-cyberflashing-dick-pics

here my tested few examples

they get  same score almost  5%

![a](https://github.com/bumble-tech/private-detector/assets/19240467/00238747-c16f-4782-865a-096a31e67083)


![b](https://github.com/bumble-tech/private-detector/assets/19240467/a1310734-aadb-4f97-8ab4-71e6e729e04d)

**Comment by Steeeephen** [comment]
![image](https://github.com/bumble-tech/private-detector/assets/18271292/1f0f4ca2-65e5-40a6-8af7-c5fa03035093)

https://dictionary.cambridge.org/dictionary/english/cyber-flashing

**Comment by FurkanGozukara** [comment]
@Steeeephen i didnt understand your answer

these images are from unsplash com even available to use commercially
